- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/hyperlnd.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/zsh.yml
