---
- name: Update APT package index
  apt:
    update_cache: yes

- name: Install required packages for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker's official GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    creates: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update APT package index (post repository addition)
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes
