- name: Add universe repository
  become: true
  command: add-apt-repository -y universe

- name: Update package lists
  become: true
  apt:
    update_cache: yes

- name: Install Hyprland
  become: true
  apt:
    name: hyprland
    state: present
