- name: Ensure Neovim is installed
  become: true
  apt:
    name: neovim
    state: present
  tags:
    - install
    - neovim

- name: Ensure Neovim configuration directory exists
  file:
    path: "{{ neovim_config_dir }}"
    state: directory
    mode: "0755"
  tags:
    - neovim

- name: Clone LazyVim repository
  git:
    repo: "{{ lazyvim_repo }}"
    dest: "{{ lazyvim_dir }}"
    update: yes
  tags:
    - neovim

- name: Install LazyVim plugins
  shell: nvim --headless +Lazy! sync +qa
  args:
    chdir: "{{ lazyvim_dir }}"
  environment:
    XDG_CONFIG_HOME: "{{ ansible_env.HOME }}/.config"
    XDG_DATA_HOME: "{{ ansible_env.HOME }}/.local/share"
    XDG_CACHE_HOME: "{{ ansible_env.HOME }}/.cache"
  tags:
    - neovim

- name: Verify LazyVim installation
  shell: nvim --headless +checkhealth +qa
  register: lazyvim_health_output
  ignore_errors: yes
  tags:
    - verify

- name: Display LazyVim health check results
  debug:
    var: lazyvim_health_output.stdout
  tags:
    - verify
