- name: Ensure Neovim is installed
  become: true
  apt:
    name: neovim
    state: present
  tags:
    - install
    - neovim

- name: Check if Neovim configuration directory exists
  stat:
    path: "{{ lazyvim_dir }}"
  register: neovim_config_stat

- name: Remove conflicting file if it exists
  file:
    path: "{{ lazyvim_dir }}"
    state: absent
  when: neovim_config_stat.stat.exists and not neovim_config_stat.stat.isdir
  tags:
    - neovim

- name: Clone LazyVim starter repository
  git:
    repo: "{{ lazyvim_repo }}"
    dest: "{{ lazyvim_dir }}"
    update: yes
  tags:
    - neovim

- name: Install LazyVim plugins
  shell: nvim --headless +Lazy! sync +qa
  args:
    chdir: "{{ lazyvim_dir }}"
  tags:
    - neovim

- name: Verify LazyVim installation
  shell: nvim --headless +checkhealth +qa
  register: lazyvim_health_output
  ignore_errors: yes
  tags:
    - verify

- name: Display LazyVim health check results
  debug:
    var: lazyvim_health_output.stdout
  tags:
    - verify
