- name: Install Neovim prerequisites
  apt:
    name:
      - neovim
      - git # Ensure git is installed for cloning
    state: present
    update_cache: yes

- name: Ensure LazyVim directory exists
  file:
    path: "{{ lazyvim_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  failed_when: false

- name: Clone LazyVim repository
  git:
    repo: "{{ lazyvim_repo }}"
    dest: "{{ lazyvim_dir }}"
    version: main
    update: yes
  become: no # Run as current user

- name: Remove existing neovim config directory
  file:
    path: "{{ neovim_config_dir }}"
    state: absent

- name: Create a symlink for nvim config
  file:
    src: "{{ lazyvim_dir }}"
    dest: "{{ neovim_config_dir }}"
    state: link
    force: yes

- name: Ensure init.lua directory exists
  file:
    path: "{{ neovim_config_dir }}"
    state: directory
    mode: "0755"

- name: Set up basic LazyVim settings
  copy:
    content: |
      lua << EOF
      -- LazyVim base configurations
      require("lazyvim.config").init()
      EOF
    dest: "{{ neovim_config_dir }}/init.lua"
    mode: "0644"

- name: Verify Neovim installation
  shell: "nvim --version"
  register: nvim_version
  changed_when: false

- name: Display Neovim version
  debug:
    var: nvim_version.stdout_lines[0:2] # Show just the first few lines of version info
