- name: Ensure Neovim is installed
  become: true
  apt:
    name: neovim
    state: present
  tags:
    - install
    - neovim

- name: Remove existing ~/.config/nvim directory if it exists
  file:
    path: /home/robdominguez/.config/nvim
    state: absent
  become: false
  tags:
    - neovim

- name: Clone LazyVim starter repository
  git:
    repo: https://github.com/LazyVim/starter.git
    dest: /home/robdominguez/.config/nvim
    update: yes
  become: false
  tags:
    - neovim

- name: Create plugins directory
  file:
    path: /home/robdominguez/.config/nvim/lua/plugins
    state: directory
    mode: "0755"
  become: false
  tags:
    - plugins

- name: Install LazyVim plugins
  shell: nvim --headless +Lazy! sync +qa
  args:
    chdir: /home/robdominguez/.config/nvim
  become: false
  tags:
    - neovim
