- name: Ensure Neovim is installed
  become: true
  apt:
    name: neovim
    state: present
  tags:
    - install
    - neovim

- name: Clone LazyVim starter repository
  git:
    repo: https://github.com/LazyVim/starter.git
    dest: ~/.config/nvim
    update: yes
  tags:
    - neovim

- name: Create plugins directory
  file:
    path: "~/.config/nvim/lua/plugins"
    state: directory
    mode: "0755"
  tags:
    - plugins

- name: Install LazyVim plugins
  shell: nvim --headless +Lazy! sync +qa
  args:
    chdir: ~/.config/nvim
  tags:
    - neovim
