- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: npmjs prefix
  become: true
  shell: mkdir -p ~/.local/.npm-global
  tags:
    - install
    - node

- name: add npmjs to path
  become: true
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
    - install
    - node
