- name: Ensure ZSH is installed
  become: true
  apt:
    name: zsh
    state: present
  tags: &tags_for_zsh_tasks ["install", "productivity", "dotfiles", "zsh"]

- name: Set zsh as default shell for robdominguez
  become: true
  user:
    name: robdominguez
    shell: /usr/bin/zsh
  tags: *tags_for_zsh_tasks

- name: Check if Oh-My-Zsh directory exists
  stat:
    path: /home/robdominguez/.oh-my-zsh
  register: oh_my_zsh_stats
  tags: *tags_for_zsh_tasks

- name: Install Oh-My-Zsh if not installed
  shell: |
    curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
  become: true
  become_user: robdominguez
  tags: *tags_for_zsh_tasks
  when: oh_my_zsh_stats.stat.exists == False

- name: Ensure .zshrc exists and is configured
  copy:
    dest: /home/robdominguez/.zshrc
    content: |
      # Path to your Oh My Zsh installation
      export ZSH="/home/robdominguez/.oh-my-zsh"

      # Set the name of the theme to load
      ZSH_THEME="robbyrussell"

      # Which plugins would you like to load?
      plugins=(git zsh-autosuggestions)

      # Source Oh My Zsh
      source $ZSH/oh-my-zsh.sh
  owner: robdominguez
  group: robdominguez
  mode: "0644"
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/robdominguez/.oh-my-zsh/plugins/zsh-autosuggestions"
  become: true
  become_user: robdominguez
  tags: *tags_for_zsh_tasks

- name: Reload ZSH configuration
  shell: zsh -c "source /home/robdominguez/.zshrc"
  become: false
  tags: *tags_for_zsh_tasks
